version: "3.9"
   
services:
  web-scheduler-1:
    container_name: scheduler1
    build: .
    command: python manage.py runserver 0.0.0.0:8000 --noreload
    volumes:
      - .:/code
    ports:
      - "8010:8000"
    networks:
      django-network:
        ipv4_address: 172.18.0.5
  web-scheduler-2:
    container_name: scheduler2
    build: .
    command: python manage.py runserver 0.0.0.0:8000 --noreload
    volumes:
      - .:/code
    ports:
      - "8011:8000"
    networks:
      django-network:
        ipv4_address: 172.18.0.6
  web-scheduler-3:
    container_name: scheduler3
    build: .
    command: python manage.py runserver 0.0.0.0:8000 --noreload
    volumes:
      - .:/code
    ports:
      - "8012:8000"
    networks:
      django-network:
        ipv4_address: 172.18.0.7
networks:
  django-network:
    external: true