version: "3.9"
   
services:
  scheduler-1:
    container_name: scheduler1
    build: .
    command: python manage.py runserver 0.0.0.0:8000 --noreload
    volumes:
      - .:/code
    ports:
      - "8010:8000"
    networks:
      servicenet:
        ipv4_address: 172.28.0.5
  scheduler-2:
    container_name: scheduler2
    build: .
    command: python manage.py runserver 0.0.0.0:8000 --noreload
    volumes:
      - .:/code
    ports:
      - "8011:8000"
    networks:
      servicenet:
        ipv4_address: 172.28.0.6
  scheduler-3:
    container_name: scheduler3
    build: .
    command: python manage.py runserver 0.0.0.0:8000 --noreload
    volumes:
      - .:/code
    ports:
      - "8012:8000"
    networks:
      servicenet:
        ipv4_address: 172.28.0.7
networks:
  servicenet:
    external: true