# Generated by Django 4.1 on 2022-08-31 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('desctiption', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='BackupPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=50)),
                ('status', models.CharField(default='NEW_CREATE', max_length=10)),
                ('job_state', models.JSONField()),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbascore.databaseinstance')),
            ],
        ),
    ]
