# Generated by Django 4.1 on 2022-09-03 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbascore', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='backuppolicy',
            old_name='job_name',
            new_name='job_id',
        ),
        migrations.AlterField(
            model_name='backuppolicy',
            name='status',
            field=models.CharField(default='NEW', max_length=10),
        ),
    ]
