# Generated by Django 4.1 on 2022-09-03 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbascore', '0002_rename_job_name_backuppolicy_job_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='databaseinstance',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
