# Generated by Django 4.1.1 on 2022-09-13 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbascore', '0003_databaseinstance_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backuppolicy',
            name='instance',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dbascore.databaseinstance'),
        ),
        migrations.AlterField(
            model_name='backuppolicy',
            name='job_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
