version: '3.9'

services:
  mariadb:
    image: mariadb
    container_name: maria1
    restart:  always
    # command: --default-authentication-plugin=mysql_native-password
    # volumes:
      # - ./database-init:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=my_first_database
      - MYSQL_ROOT_PASSWORD=1
      - MYSQL_USER=root
      - MYSQL_PASSWORD=1
      - MYSQL_HOST=172.28.0.2
    networks:
      servicenet:
        ipv4_address: 172.28.0.2
  redis:
    image: redis
    container_name: redis1
    networks:
      servicenet:
        ipv4_address: 172.28.0.3
networks:
  servicenet:
    external: true
