# Generated by Django 4.1 on 2022-09-21 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CronJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(default='random-id-generate', max_length=255, unique=True)),
                ('instance', models.CharField(max_length=100, null=True)),
                ('zone', models.CharField(default='UTC', max_length=20)),
                ('cron_time', models.CharField(help_text='UNIX cron format: minute hour day_of_month month day_of_week', max_length=50)),
                ('next_execution_time', models.DateTimeField(null=True)),
                ('status', models.CharField(choices=[('ENABLED', 'ENABLED'), ('DISABLED', 'DISABLED')], default='ENABLED', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='JobExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(null=True)),
                ('stop_time', models.DateTimeField(null=True)),
                ('status', models.CharField(default='SUCCESS', max_length=10)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cronjob')),
            ],
        ),
    ]
