version: '3.9'

services:
  mariadb:
    image: mariadb
    container_name: z-test-mariadb
    volumes:
      - ./init/maria-init.sh:/docker-entrypoint.sh
    environment:
      - MYSQL_DATABASE=dbasdjango
      - MYSQL_ROOT_PASSWORD=1
      - MYSQL_USER=root
      - MYSQL_PASSWORD=1